spring:
  application:
    name: easystay
  datasource:
#    url: jdbc:oracle:thin:@//192.168.234.130:1521/freepdb1
#    username: hr
#    password: oracle
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: c##abdullah
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: yNcWGArQWpoh4lHACl/cbhnWdgCv9ML92Rq+SMnl3zc=
  expiry: 8640000
#spring:
#  application:
#    name: easystay
#
#  datasource:
#    # H2 in-memory database
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#    # 🔴 Oracle (disabled)
#    # url: jdbc:oracle:thin:@//localhost:1521/orcl
#    # username: c##abdullah
#    # password: password123
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop   # or update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jwt:
#    secret: yNcWGArQWpoh4lHACl/cbhnWdgCv9ML92Rq+SMnl3zc=
#    expiry: 8640000